# Generated by Django 2.0.2 on 2018-03-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('attack_power', models.IntegerField(default=0)),
                ('defense_power', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('culture', models.IntegerField(default=0)),
                ('science', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
