# Generated by Django 2.0.2 on 2018-03-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_buildable',
            field=models.BooleanField(default=True),
        ),
    ]
